apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-operators-application
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multicluster-operators-application
  template:
    metadata:
      labels:
        name: multicluster-operators-application
    spec:
      serviceAccountName: multicluster-operators-application
      containers:
        - name: multicluster-operators-application
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - multicluster-operators-application
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "multicluster-operators-application"
